// ===== Schema.gs =====
// SGE v2.1.0 - Ficha integral del emprendedor
// Definición del esquema de tablas en Google Sheets, catálogos iniciales y permisos RBAC

const SCHEMA = Object.freeze({
  PERSONAS: [
    'ID_PERSONA', 'RUT_NORMALIZADO', 'NOMBRES', 'APELLIDO_PATERNO', 'APELLIDO_MATERNO',
    'FECHA_NACIMIENTO', 'GENERO', 'DISCAPACIDAD_DECLARADA', 'TELEFONO_NORMALIZADO',
    'EMAIL_NORMALIZADO', 'COMUNA_RESIDENCIA', 'ESTADO_REGISTRO', 'CREADO_EN',
    'CREADO_POR', 'ACTUALIZADO_EN', 'ACTUALIZADO_POR', 'CODIGO_PERSONA'
  ],
  EMPRENDIMIENTOS: [
    'ID_EMPRENDIMIENTO', 'NOMBRE_COMERCIAL', 'DESCRIPCION', 'ID_RUBRO', 'ID_SUBRUBRO',
    'FECHA_INICIO_ESTIMADA', 'FORMALIZACION', 'DEDICACION', 'CANAL_VENTA', 'ETAPA_ACTUAL',
    'TERRITORIO_OPERACION', 'ESTADO_EMPRENDIMIENTO', 'CREADO_EN', 'CREADO_POR',
    'ACTUALIZADO_EN', 'ACTUALIZADO_POR', 'CODIGO_EMPRENDIMIENTO', 'INSTAGRAM',
    'FACEBOOK', 'TIKTOK', 'SITIO_WEB', 'ORIGEN_ATENCION'
  ],
  PERSONA_EMPRENDIMIENTO: [
    'ID_RELACION', 'ID_PERSONA', 'ID_EMPRENDIMIENTO', 'ROL', 'ES_PRINCIPAL',
    'DESDE', 'HASTA', 'ESTADO_REGISTRO', 'CREADO_EN', 'CREADO_POR'
  ],
  DIRECCIONES: [
    'ID_DIRECCION', 'TIPO_SUJETO', 'ID_SUJETO', 'TIPO_DIRECCION', 'DIRECCION_DECLARADA',
    'DIRECCION_NORMALIZADA', 'COMUNA', 'BARRIO', 'ESTADO_VALIDACION', 'ES_VIGENTE',
    'CREADO_EN', 'CREADO_POR'
  ],
  GEOLOCALIZACIONES: [
    'ID_GEOLOCALIZACION', 'ID_DIRECCION', 'LATITUD', 'LONGITUD', 'PRECISION',
    'FUENTE', 'FECHA_GEOCODIFICACION', 'ESTADO_VALIDACION', 'CREADO_POR'
  ],
  DOCUMENTOS: [
    'ID_DOCUMENTO', 'TIPO_SUJETO', 'ID_SUJETO', 'TIPO_DOCUMENTO', 'ID_ARCHIVO_DRIVE',
    'VERSION', 'FECHA_EMISION', 'FECHA_VENCIMIENTO', 'ESTADO_REVISION', 'REVISADO_POR',
    'REVISADO_EN', 'MOTIVO_OBSERVACION', 'ES_VERSION_VIGENTE', 'CREADO_EN',
    'CREADO_POR', 'HUELLA_ARCHIVO'
  ],
  DOCUMENTOS_INICIATIVA: [
    'ID_DOCUMENTO_INICIATIVA', 'ID_INICIATIVA', 'TIPO_DOCUMENTO', 'ID_ARCHIVO_DRIVE',
    'NOMBRE_ARCHIVO', 'ESTADO_REVISION', 'OBSERVACION', 'CREADO_EN', 'CREADO_POR'
  ],
  INICIATIVAS: [
    'ID_INICIATIVA', 'TIPO_INICIATIVA', 'NOMBRE', 'OBJETIVO', 'TEMATICA',
    'APERTURA_POSTULACION', 'CIERRE_POSTULACION', 'FECHA_EJECUCION', 'LUGAR',
    'ID_DIRECCION', 'CUPOS_TITULARES', 'CUPOS_SUPLENTES', 'VERSION_REGLAS',
    'ESTADO', 'RESPONSABLE', 'CREADO_EN', 'CREADO_POR', 'BARRIO',
    'ENTIDAD_ORGANIZADORA', 'ID_CARPETA_DRIVE', 'URL_FORMULARIO_POSTULACION'
  ],
  REQUISITOS: [
    'ID_REQUISITO', 'ID_INICIATIVA', 'VERSION_REGLAS', 'TIPO_REGLA', 'CAMPO',
    'OPERADOR', 'VALOR_ESPERADO', 'ES_SUBSANABLE', 'ORDEN', 'ACTIVO',
    'CREADO_EN', 'CREADO_POR'
  ],
  POSTULACIONES: [
    'ID_POSTULACION', 'ID_INICIATIVA', 'ID_EMPRENDIMIENTO', 'ID_PERSONA_CONTACTO',
    'FECHA_POSTULACION', 'ESTADO_POSTULACION', 'RESPUESTAS_JSON', 'CREADO_EN',
    'CREADO_POR', 'ACTUALIZADO_EN', 'ACTUALIZADO_POR'
  ],
  ADMISIONES: [
    'ID_ADMISION', 'ID_POSTULACION', 'ID_REQUISITO', 'RESULTADO', 'RESULTADO_REGLA',
    'MOTIVO_EXCLUSION', 'EVALUADO_EN', 'EVALUADO_POR', 'ID_EJECUCION_ADMISION', 'ES_VIGENTE'
  ],
  PROCESOS_SELECCION: [
    'ID_PROCESO', 'ID_INICIATIVA', 'VERSION_REGLAS', 'METODO', 'PARAMETROS_JSON',
    'SEMILLA', 'FECHA_EJECUCION', 'EJECUTADO_POR', 'ESTADO', 'TAMANO_UNIVERSO', 'HUELLA_INTEGRIDAD'
  ],
  UNIVERSO_SELECCION: [
    'ID_UNIVERSO', 'ID_PROCESO', 'ID_POSTULACION', 'ELEGIBLE', 'ESTRATO',
    'PONDERACION', 'ORDEN_ALEATORIO', 'MOTIVO_EXCLUSION', 'CREADO_EN'
  ],
  RESULTADOS_SELECCION: [
    'ID_RESULTADO', 'ID_PROCESO', 'ID_POSTULACION', 'RESULTADO', 'POSICION',
    'ESTRATO', 'FECHA_RESULTADO', 'PROCESO_ORIGEN'
  ],
  AJUSTES_SELECCION: [
    'ID_AJUSTE', 'ID_PROCESO', 'ID_RESULTADO', 'ESTADO_ANTERIOR', 'ESTADO_NUEVO',
    'MOTIVO', 'EVIDENCIA', 'AUTORIZADO_POR', 'FECHA_AJUSTE'
  ],
  PARTICIPACIONES: [
    'ID_PARTICIPACION', 'ID_RESULTADO', 'ID_POSTULACION', 'ESTADO_PARTICIPACION',
    'FECHA_CONFIRMACION', 'FECHA_ASISTENCIA', 'MOTIVO', 'REEMPLAZA_A', 'CREADO_EN', 'CREADO_POR'
  ],
  SEGUIMIENTO_MERCADO: [
    'ID_SEGUIMIENTO', 'ID_INICIATIVA', 'ID_EMPRENDIMIENTO', 'ID_POSTULACION',
    'FECHA_REGISTRO', 'VENTAS_ANTES', 'VENTAS_DURANTE', 'VENTAS_DESPUES',
    'SEGUIDORES_ANTES', 'SEGUIDORES_DESPUES', 'PUNTUALIDAD', 'RESPONSABILIDAD',
    'EVALUACION_FUNCIONARIO', 'OBSERVACION', 'REGISTRADO_POR', 'TIPO_AYUDA'
  ],
  BENEFICIOS: [
    'ID_BENEFICIO', 'ID_EMPRENDIMIENTO', 'ID_INICIATIVA', 'TIPO_BENEFICIO',
    'CANTIDAD', 'MONTO', 'FECHA', 'FUENTE', 'RESPONSABLE'
  ],
  ATENCIONES: [
    'ID_ATENCION', 'FECHA', 'ID_USUARIO', 'ID_PERSONA', 'ID_EMPRENDIMIENTO',
    'NECESIDAD', 'DIAGNOSTICO', 'ESTADO', 'OBSERVACION'
  ],
  DERIVACIONES: [
    'ID_DERIVACION', 'ID_ATENCION', 'ORIGEN', 'DESTINO', 'MOTIVO',
    'FECHA', 'RESULTADO', 'SEGUIMIENTO'
  ],
  COMUNICACIONES: [
    'ID_COMUNICACION', 'FECHA', 'TIPO_DESTINATARIO', 'ID_INICIATIVA',
    'FILTROS_JSON', 'CANTIDAD_DESTINATARIOS', 'ASUNTO_REFERENCIA', 'REGISTRADO_POR'
  ],
  EVALUACIONES_EMPRENDIMIENTO: [
    'ID_EVALUACION', 'ID_EMPRENDIMIENTO', 'FECHA_EVALUACION', 'PUNTAJE',
    'DIMENSIONES_JSON', 'CLASIFICACION', 'BRECHAS', 'MOTIVACION', 'DEDICACION',
    'NECESIDAD_PRIORITARIA', 'PROXIMA_REVISION', 'EVALUADO_POR'
  ],
  CLASIFICACION_HISTORICA: [
    'ID_HISTORIAL', 'ID_EMPRENDIMIENTO', 'ID_EVALUACION', 'CLASIFICACION_ANTERIOR',
    'CLASIFICACION_NUEVA', 'DESDE', 'HASTA', 'MOTIVO', 'REGISTRADO_POR'
  ],
  USUARIOS: [
    'ID_USUARIO', 'EMAIL', 'NOMBRE', 'ROL', 'ACTIVO', 'CREADO_EN', 'CREADO_POR'
  ],
  ROLES: [
    'ROL', 'DESCRIPCION', 'PERMISOS_JSON'
  ],
  AUDITORIA: [
    'ID_EVENTO_AUDITORIA', 'FECHA_HORA', 'ID_USUARIO', 'ROL', 'ACCION',
    'ENTIDAD', 'ID_REGISTRO', 'VALOR_ANTERIOR', 'VALOR_NUEVO', 'MOTIVO', 'ID_CORRELACION'
  ],
  CATALOGOS: [
    'TIPO_CATALOGO', 'CODIGO', 'ETIQUETA', 'ORDEN', 'ACTIVO', 'METADATA_JSON'
  ],
  CONFIGURACION: [
    'CLAVE', 'VALOR', 'DESCRIPCION', 'ACTUALIZADO_EN', 'ACTUALIZADO_POR'
  ],
  LOG_ERRORES: [
    'ID_ERROR', 'FECHA_HORA', 'USUARIO', 'FUNCION', 'MENSAJE', 'STACK', 'ID_CORRELACION'
  ],
  REGISTROS_FORMULARIO: [
    'ID_REGISTRO_FORMULARIO', 'FECHA_RECEPCION', 'ORIGEN', 'ID_RESPUESTA',
    'ID_PERSONA', 'ID_EMPRENDIMIENTO', 'RESULTADO', 'DETALLE', 'PROCESADO_EN'
  ]
});

const CATALOGOS_INICIALES = Object.freeze({
  ETAPA_EMPRENDIMIENTO: ['ARRANQUE', 'DESARROLLO', 'CONSOLIDACION'],
  ESTADO_EMPRENDIMIENTO: ['ACTIVO', 'ESTACIONAL', 'SUSPENDIDO', 'CERRADO'],
  FORMALIZACION: ['SIN_INICIO', 'INICIO_ACTIVIDADES', 'PATENTE', 'PERSONA_JURIDICA'],
  ORIGEN_ATENCION: ['DEMANDA', 'CASO_SOCIAL', 'ALCALDIA', 'LOBBY', 'OTRO'],
  DEDICACION: ['PRINCIPAL', 'COMPLEMENTARIA', 'ESTACIONAL'],
  RUBRO: [
    'ALIMENTACION', 'ARTESANIA', 'TEXTIL', 'BELLEZA_CUIDADO_PERSONAL',
    'COMERCIO', 'SERVICIOS', 'TECNOLOGIA', 'TURISMO', 'ECONOMIA_CIRCULAR', 'OTRO'
  ],
  SUBRUBRO: [
    'COMIDA_PREPARADA', 'COLACIONES_COFFEE_BREAK', 'PANADERIA_PASTELERIA', 'REPOSTERIA',
    'PRODUCTOS_GOURMET', 'CONSERVAS_ENCURTIDOS', 'BEBESTIBLES', 'ARTESANIA_TRADICIONAL',
    'CERAMICA_ALFARERIA', 'MADERA', 'CUERO', 'JOYERIA_BISUTERIA', 'TEJIDOS',
    'CONFECCION_VESTUARIO', 'BOLSOS_ACCESORIOS_TEXTILES', 'CALZADO', 'DECORACION_HOGAR',
    'ILUSTRACION_DISENO', 'COSMETICA_NATURAL', 'PELUQUERIA_BARBERIA', 'MANICURE_ESTETICA',
    'BIENESTAR_CUIDADO_PERSONAL', 'ALMACEN_REGALERIA', 'LIBRERIA_PAPELERIA',
    'REVENTA_COMERCIO', 'ASESORIAS_PROFESIONALES', 'SERVICIOS_PERSONALES',
    'OFICIOS_REPARACIONES', 'DESARROLLO_WEB_SOFTWARE', 'MARKETING_DISENO_DIGITAL',
    'TECNOLOGIA_SERVICIOS_DIGITALES', 'TURISMO_EXPERIENCIAS', 'GASTRONOMIA_TURISTICA',
    'RECICLAJE_REUTILIZACION', 'PRODUCTOS_SUSTENTABLES', 'OTRO'
  ],
  CANAL_VENTA: ['FERIAS', 'TIENDA_FISICA', 'REDES_SOCIALES', 'MARKETPLACE', 'SITIO_WEB', 'MAYORISTA', 'OTRO'],
  TIPO_DOCUMENTO_PERSONA: ['CEDULA_IDENTIDAD_COMPLETA', 'REGISTRO_SOCIAL_HOGARES', 'ACREDITACION_DISCAPACIDAD', 'OTRO'],
  TIPO_DOCUMENTO_EMPRENDIMIENTO: [
    'INICIO_ACTIVIDADES', 'PATENTE_COMERCIAL', 'FICHA_TECNICA_PRODUCTOS',
    'FOTOGRAFIA_PRODUCTOS', 'CONSTITUCION_EMPRESA', 'CERTIFICADO_SANITARIO', 'OTRO'
  ],
  TIPO_DOCUMENTO_INICIATIVA: [
    'MINUTA', 'GRAFICA', 'PROGRAMACION', 'LIBRETO', 'FOTOS_ACTIVIDAD',
    'LISTADO_ASISTENTES', 'OTRO'
  ],
  PUNTUALIDAD: ['A_TIEMPO', 'TARDE', 'SIN_REGISTRO'],
  RESPONSABILIDAD: ['DESTACADA', 'ADECUADA', 'OBSERVADA', 'SIN_REGISTRO'],
  EVALUACION_FUNCIONARIO: ['DESTACADO', 'ADECUADO', 'REQUIERE_APOYO', 'NO_EVALUADO'],
  ESTADO_INICIATIVA: ['BORRADOR', 'ABIERTA', 'CERRADA', 'EN_EJECUCION', 'FINALIZADA', 'CANCELADA'],
  TIPO_REGLA: ['ADMISIBILIDAD', 'PRIORIZACION'],
  CAMPO_REQUISITO: [
    'ID_RUBRO', 'ID_SUBRUBRO', 'FORMALIZACION', 'ETAPA_ACTUAL', 'ESTADO_EMPRENDIMIENTO',
    'COMUNA_PERSONA', 'GENERO_PERSONA', 'DISCAPACIDAD_DECLARADA',
    'DOCUMENTACION_PERSONA_COMPLETA', 'DOCUMENTACION_EMPRENDIMIENTO_COMPLETA',
    'HABILITADO_MERCADOS'
  ],
  OPERADOR_REQUISITO: ['IGUAL', 'IN', 'NO_IN', 'MAYOR_IGUAL', 'MENOR_IGUAL', 'EXISTE'],
  TIPO_INICIATIVA: ['MERCADO', 'FERIA', 'EVENTO', 'PROGRAMA', 'FONDO'],
  ESTADO_DOCUMENTO: ['RECIBIDO', 'VIGENTE', 'OBSERVADO', 'POR_VENCER', 'VENCIDO', 'RECHAZADO', 'REEMPLAZADO'],
  ESTADO_POSTULACION: ['BORRADOR', 'RECIBIDA', 'EN_REVISION', 'SUBSANABLE', 'ADMISIBLE', 'INADMISIBLE', 'RETIRADA'],
  RESULTADO_SELECCION: ['TITULAR', 'SUPLENTE', 'NO_SELECCIONADO', 'EXCLUIDO'],
  ESTADO_PARTICIPACION: ['PENDIENTE', 'CONFIRMADA', 'NO_RESPONDE', 'ASISTIO', 'INASISTENTE', 'DESISTIO', 'REEMPLAZADA'],
  TIPO_DIRECCION: ['PARTICULAR', 'COMERCIAL', 'PRODUCCION', 'NOTIFICACION'],
  ESTADO_VALIDACION: ['DECLARADO', 'VALIDADO', 'OBSERVADO', 'PENDIENTE'],
  ESTADO_REGISTRO: ['ACTIVO', 'INACTIVO', 'OBSERVADO', 'POSIBLE_DUPLICADO'],
  ROL_REPRESENTACION: ['TITULAR', 'REPRESENTANTE', 'SOCIO', 'CONTACTO'],
  TIPO_AYUDA: ['PUNTO_DE_VENTA', 'ASESORIA', 'PUNTO_DE_VENTA_Y_ASESORIA', 'OTRO']
});

const ETIQUETAS_CATALOGO = Object.freeze({
  PUNTO_DE_VENTA: 'Punto de venta (puesto en feria/mercado)',
  ASESORIA: 'Asesoría / Capacitación / Acompañamiento',
  PUNTO_DE_VENTA_Y_ASESORIA: 'Punto de venta y Asesoría',
  OTRO_APOYO: 'Otro apoyo municipal',
  ARRANQUE: 'Etapa inicial',
  DESARROLLO: 'En desarrollo',
  CONSOLIDACION: 'Consolidado',
  SIN_INICIO: 'Sin inicio de actividades',
  INICIO_ACTIVIDADES: 'Con inicio de actividades',
  PATENTE: 'Con patente comercial',
  PERSONA_JURIDICA: 'Persona jurídica',
  CEDULA_IDENTIDAD_FRONTAL: 'Cédula de identidad - frontal',
  CEDULA_IDENTIDAD_REVERSO: 'Cédula de identidad - reverso',
  CEDULA_IDENTIDAD_COMPLETA: 'Cédula por ambos lados (único archivo)',
  REGISTRO_SOCIAL_HOGARES: 'Registro Social de Hogares',
  ACREDITACION_DISCAPACIDAD: 'Credencial de discapacidad o pensión de invalidez',
  FICHA_TECNICA_PRODUCTOS: 'Ficha técnica de productos o servicios',
  FOTOGRAFIA_PRODUCTOS: 'Fotografías de productos',
  MINUTA: 'Minuta',
  GRAFICA: 'Gráfica',
  PROGRAMACION: 'Programación',
  LIBRETO: 'Libreto',
  FOTOS_ACTIVIDAD: 'Fotos de la actividad',
  LISTADO_ASISTENTES: 'Listado de emprendimientos asistentes',
  ADMISIBILIDAD: 'Admisibilidad',
  PRIORIZACION: 'Priorización',
  ID_RUBRO: 'Rubro del emprendimiento',
  ID_SUBRUBRO: 'Subrubro del emprendimiento',
  FORMALIZACION: 'Nivel de formalización',
  ETAPA_ACTUAL: 'Etapa de desarrollo',
  ORIGEN_ATENCION: 'Origen de la atención',
  HABILITADO_MERCADOS: 'Habilitación para mercados DIDEL',
  ESTADO_EMPRENDIMIENTO: 'Estado del emprendimiento',
  COMUNA_PERSONA: 'Comuna de residencia',
  GENERO_PERSONA: 'Género declarado',
  DISCAPACIDAD_DECLARADA: 'Discapacidad declarada',
  DOCUMENTACION_PERSONA_COMPLETA: 'Copia de cédula completa',
  DOCUMENTACION_EMPRENDIMIENTO_COMPLETA: 'Documentación del emprendimiento completa',
  IGUAL: 'Es igual a',
  IN: 'Está dentro de',
  NO_IN: 'No está dentro de',
  MAYOR_IGUAL: 'Es mayor o igual a',
  MENOR_IGUAL: 'Es menor o igual a',
  EXISTE: 'Tiene información registrada',
  ALEATORIO_SIMPLE: 'Sorteo aleatorio simple',
  ALEATORIO_ESTRATIFICADO: 'Sorteo por grupos',
  RANKING_PUNTAJE: 'Orden por puntaje'
});

const EXPLICACION_OPERADORES = Object.freeze({
  IGUAL: 'Cumple cuando el dato coincide exactamente con el valor esperado.',
  IN: 'Cumple cuando el dato está en una lista de alternativas separadas por |.',
  NO_IN: 'Cumple cuando el dato no aparece en la lista de alternativas.',
  MAYOR_IGUAL: 'Cumple cuando el número registrado es igual o superior al mínimo.',
  MENOR_IGUAL: 'Cumple cuando el número registrado es igual o inferior al máximo.',
  EXISTE: 'Cumple cuando el campo contiene cualquier información.'
});

const PERMISOS_ROL = Object.freeze({
  ADMIN: ['*'],
  GESTOR: [
    'PERSONA_VER', 'PERSONA_EDITAR', 'EMPRENDIMIENTO_VER', 'EMPRENDIMIENTO_EDITAR',
    'DOCUMENTO_CARGAR', 'DOCUMENTO_VER_SENSIBLE', 'DOCUMENTO_REVISAR',
    'INICIATIVA_EDITAR', 'POSTULACION_EDITAR', 'PARTICIPACION_EDITAR',
    'SELECCION_EJECUTAR', 'SELECCION_VER', 'REPORTE_VER', 'EXPORTAR_IDENTIFICABLE'
  ]
});
